version: '3.8'

services:
  db:  # Это наша база данных
    image: postgres:15   # Используем PostgreSQL 15
    environment:
      POSTGRES_USER: user     # Логин для БД
      POSTGRES_PASSWORD: 1234 # Пароль (смените на свой)
      POSTGRES_DB: flats # Название БД
    ports:
      - "5432:5432"  # Открываем порт для подключения
    volumes:
      - db_data:/var/lib/postgresql/data  # Сохраняем данные БД
  parser:
    build:               # Контекст сборки — корень проекта
      dockerfile: parsing/Dockerfile   # Путь к Dockerfile внутри контекста
    command: python main.py

volumes:
  db_data:  # Это нужно, чтобы данные не пропадали при перезапуске