services:
  db:  # Это наша база данных
    image: postgres:15   # Используем PostgreSQL 15
    ports:
      - "5432:5432"  # Открываем порт для подключения
    volumes:
      - db_data:/var/lib/postgresql/data  # Сохраняем данные БД
  parser:
    build:
      context: . # Контекст сборки — корень проекта
      dockerfile: parsing/Dockerfile   # Путь к Dockerfile внутри контекста
    env_file: .env
    container_name: parser
    environment:
      - PYTHONPATH=/parser
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./Backend/Dockerfile
    depends_on:
      - db
    env_file: .env
    environment:
      PYTHONPATH: .
    ports:
      - "5000:5000"
    command: gunicorn --bind 0.0.0.0:5000 Backend.main:app
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  db_data:  # Это нужно, чтобы данные не пропадали при перезапуске