name: Daily Parser

on:
  schedule:
    - cron: '0 6 * * *'  # Ежедневно в 6:00 UTC
  workflow_dispatch:

jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -f parsing/Dockerfile -t parser .

      - name: Run parser
        run: |
          docker run --rm parser python main.py